version: "3.5"
services:
  whatsapp_client_dev_container:
    privileged: true # Para invocar o CLI docker
    user: developer
    container_name: whatsapp_client_dev_container
    image: whatsapp_client_dev_container
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
      args:
        - HOST_DOCKER_GROUP_ID=${HOST_DOCKER_GROUP_ID}
    restart: on-failure
    environment:
      - DEV_ROOT_DIR=${DEV_ROOT_DIR}
    volumes:
      - type: bind
        source: ..
        target: /home/developer/dev
      #Para invocar o CLI do docker
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    network_mode: 'host'
    #Quando essa instrução terminar o container fecha
    command: /bin/sh -c "while sleep 1000; do :; done"