name: Update

on:
  schedule:
    - cron: "0/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install node v14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - run: cd ./tools/version-checker
      - name: Run Updater
        run: ./update-version
      - name: Store WA Version
        run: echo WA_VERSION=`cat ./.version` >> $GITHUB_ENV
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update supported WhatsApp Web version to v${{ env.WA_VERSION }}
          title: Update WhatsApp Web Version (${{ env.WA_VERSION }})
          body: |
            A new version of WhatsApp Web has been detected! 
            
            Tests should be run against this new version before merging.
          labels: WhatsApp Change
          reviewers: pedroslopez